### ISSUE TITLE
param-gen

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/poseidon377#61]
https://github.com/penumbra-zone/poseidon377/blob/7ad1eb586ba515232104e941bfe35af088d78173/Cargo.toml#L5

@redshiftzero what's the status of this? currently getting rust-doc [failures](https://github.com/penumbra-zone/penumbra/blob/main/deployments/scripts/rust-docs#L60) when using newest decaf377 version.

**Comment by TalDerei** [comment]
additionally getting this error message when using version 1.1.0 on https://github.com/penumbra-zone/penumbra/pull/3806 when trying to execute the [test suite ](https://github.com/penumbra-zone/penumbra/actions/runs/9721806685/job/26834964732?pr=3806)

<img width="1306" alt="Screenshot 2024-06-29 at 7 35 46 PM" src="https://github.com/penumbra-zone/poseidon377/assets/70081547/0f31f123-92b0-437b-8526-57af40a34bcd">

**Comment by redshiftzero** [comment]
Closing this one - `param-gen` should not be required/used as a build-time dependency anywhere (see #58)
